###

### Create session
POST https://localhost:7197/api/Chat/sessions
accept: text/plain
Content-Type: application/x-www-form-urlencoded

### Get messages of session

# curl -X 'GET'
#  'https://localhost:7197/api/Chat/messages/838e3dcc-32c7-4c73-bdcc-27b9e1bba161'
#  -H 'accept: */*'
GET https://localhost:7197/api/Chat/messages/838e3dcc-32c7-4c73-bdcc-27b9e1bba161
accept: */*

### Post message to session

# curl -X 'POST'
#  'https://localhost:7197/api/Chat/messages/838e3dcc-32c7-4c73-bdcc-27b9e1bba161'
#  -H 'accept: */*'
#  -H 'Content-Type: application/json'
#  -d '{
#  "userPrompt": "I am looking something light for birthday party of my boyfriend"
#}'
POST https://localhost:7197/api/Chat/messages/838e3dcc-32c7-4c73-bdcc-27b9e1bba161
accept: */*
Content-Type: application/json

{
  "userPrompt": "I am looking something light for birthday party of my boyfriend"
}

###